# Generated by Django 5.2.14 on 2026-05-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_job_id_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_type',
            field=models.CharField(choices=[('Paint', 'Paint'), ('Electric', 'Electric'), ('Sewage', 'Sewage'), ('Cleaning', 'Cleaning'), ('Carpenter', 'Carpenter'), ('AC', 'AC'), ('Mason', 'Mason')], max_length=50),
        ),
    ]
