# Generated by Django 5.2.14 on 2026-05-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_type',
            field=models.CharField(choices=[('Paint', 'Paint'), ('Electric', 'Electric'), ('Plumbing', 'Plumbing'), ('Cleaning', 'Cleaning'), ('Carpenter', 'Carpenter'), ('AC', 'AC'), ('Mason', 'Mason')], max_length=50),
        ),
    ]
