# Generated by Django 5.2.14 on 2026-06-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='after_image',
        ),
        migrations.RemoveField(
            model_name='task',
            name='before_image',
        ),
    ]
