# Generated by Django 5.2.14 on 2026-06-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
