# Generated by Django 5.2.14 on 2026-06-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending (قيد الانتظار)'), ('In Progress', 'In Progress (نشط)'), ('Completed', 'Completed (مكتمل)'), ('Overdue', 'Overdue (متأخر)')], default='Pending', max_length=50),
        ),
    ]
