# Generated by Django 5.2.14 on 2026-06-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending(قيد الانتظار)', 'Pending'), ('In Progress(نشط)', 'In Progress'), ('Completed(مكتمل)', 'Completed'), ('Overdue(متأخر)', 'Overdue')], default='Pending', max_length=50),
        ),
    ]
