# Generated by Django 5.2.14 on 2026-06-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_task_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_type',
            field=models.CharField(choices=[('Paint', 'Paint'), ('Electric', 'Electric'), ('Plumbing', 'Plumbing'), ('Cleaning', 'Cleaning'), ('Carpenter', 'Carpenter'), ('AC', 'AC'), ('Mason', 'Mason'), ('Ceiling(سقف)', 'Ceiling')], max_length=50),
        ),
    ]
