# Generated by Django 5.2.14 on 2026-06-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_task_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_type',
            field=models.CharField(choices=[('Paint(صباغة)', 'Paint'), ('Electric(كهرباء)', 'Electric'), ('Plumbing(سباكة)', 'Plumbing'), ('Cleaning(تنظيف)', 'Cleaning'), ('Carpenter(نجارة)', 'Carpenter'), ('AC(تكييف)', 'AC'), ('Mason(بناء)', 'Mason'), ('Ceiling(سقف)', 'Ceiling(سقف)')], max_length=50),
        ),
    ]
