# Generated by Django 5.2.14 on 2026-06-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_task_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='is_rewarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='reward_points_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=250)),
                ('quantity', models.FloatField(default=1.0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.task')),
            ],
        ),
    ]
