# Generated by Django 5.2.14 on 2026-06-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_profile_reward_points_task_is_rewarded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_type',
            field=models.CharField(choices=[('Paint', 'Paint(صباغة)'), ('Electric', 'Electric(كهرباء)'), ('Plumbing', 'Plumbing(سباكة)'), ('Cleaning', 'Cleaning(تنظيف'), ('Carpenter', 'Carpenter(نجارة)'), ('AC', 'AC(تكييف)'), ('Mason', 'Mason(بناء)'), ('Ceiling', 'Ceiling(سقف)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward_points_awarded',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='quantity',
            field=models.TextField(),
        ),
    ]
