# Generated by Django 5.2.14 on 2026-06-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_alter_task_project_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='location',
        ),
        migrations.AddField(
            model_name='task',
            name='building',
            field=models.CharField(default='Al Naser Plaza (بلاك النصر بلازا)', help_text='Select building complex or project zone', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='custom_location',
            field=models.CharField(blank=True, help_text="Used dynamically if 'Other' is checked by user", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='unit',
            field=models.CharField(default=103, help_text='Specific flat, room, floor or system zone designation', max_length=150),
            preserve_default=False,
        ),
    ]
