# Generated by Django 5.2.14 on 2026-06-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_taskattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['project_type', 'name_english']},
        ),
        migrations.AddField(
            model_name='task',
            name='name_arabic',
            field=models.CharField(default=' -', help_text='e.g., تمديد أسلاك 2.5 مم', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='name_english',
            field=models.CharField(default=' -', help_text='e.g., Wiring 2.5 mm', max_length=150),
            preserve_default=False,
        ),
    ]
