# Generated by Django 5.2.14 on 2026-06-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_alter_task_options_task_name_arabic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='name_arabic',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name_english',
        ),
        migrations.CreateModel(
            name='MaintenanceWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('Paint', 'Paint'), ('Electric', 'Electric'), ('Plumbing', 'Plumbing'), ('Cleaning', 'Cleaning'), ('Carpenter', 'Carpenter'), ('AC', 'AC'), ('Mason', 'Mason'), ('Ceiling', 'Ceiling')], max_length=50)),
                ('name_english', models.CharField(help_text='e.g., Wiring 2.5 mm', max_length=150)),
                ('name_arabic', models.CharField(help_text='e.g., تمديد أسلاك 2.5 مم', max_length=150)),
            ],
            options={
                'ordering': ['project_type', 'name_english'],
                'unique_together': {('project_type', 'name_english')},
            },
        ),
    ]
