# Generated by Django 5.2.14 on 2026-06-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_alter_task_options_remove_task_name_arabic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceworkitem',
            name='project_type',
            field=models.CharField(choices=[('Paint', 'Paint(صباغة)'), ('Electric', 'Electric(كهرباء)'), ('Plumbing', 'Plumbing(سباكة)'), ('Cleaning', 'Cleaning(تنظيف'), ('Carpenter', 'Carpenter(نجارة)'), ('AC', 'AC(تكييف)'), ('Mason', 'Mason(بناء)'), ('Ceiling', 'Ceiling(سقف)')], max_length=50),
        ),
    ]
