# Generated by Django 5.2.14 on 2026-06-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_remove_task_assigned_to_task_assigned_technicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='final_delay_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
