# Generated by Django 5.1 on 2026-06-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_alter_task_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video for task completion verification', null=True, upload_to='task_attachments/videos/'),
        ),
    ]
