# Generated by Django 5.2.14 on 2026-07-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_taskattachment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overtime_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Additional charge for overtime in AED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Overtime logged in hours (e.g., 1.5)', max_digits=5, null=True),
        ),
    ]
