# Generated by Django 5.2.14 on 2026-07-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_task_overtime_charge_task_overtime_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manual_ot_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Directly inputted overtime charge/bonus', max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='manual_ot_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Directly inputted loose overtime hours', max_digits=6),
        ),
    ]
