# Generated by Django 5.2.14 on 2026-07-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_materialrequest_requestedmaterialitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_overtime',
            field=models.BooleanField(default=False, help_text='Flag to explicitly pin this task to the Overtime board'),
        ),
    ]
