# Generated by Django 5.2.14 on 2026-08-03 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_task_is_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to='tasks.task'),
        ),
    ]
