# Generated by Django 5.2.14 on 2026-08-04 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_alter_materialrequest_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_request', to='tasks.task'),
        ),
    ]
