# Generated by Django 5.2.14 on 2026-08-04 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_alter_materialrequest_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='title',
            field=models.CharField(blank=True, help_text='Title or description for general requests', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_request', to='tasks.task'),
        ),
    ]
