# Generated by Django 5.2.14 on 2026-08-04 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_materialrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='is_general',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='title',
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='task',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='material_request', to='tasks.task'),
            preserve_default=False,
        ),
    ]
