# Generated by Django 5.2.14 on 2026-08-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_generalmaterialrequest_generalrequestedmaterialitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmaterialrequest',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
