# Generated by Django 5.2.14 on 2026-08-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0044_generalmaterialrequest_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='supplier',
            field=models.CharField(choices=[('Hyper', 'Hyper'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
