# Generated by Django 5.2.14 on 2026-08-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0045_materialrequest_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_type',
            field=models.CharField(choices=[('Paint', 'Paint(صباغة)'), ('Electric', 'Electric(كهرباء)'), ('Plumbing', 'Plumbing(سباكة)'), ('Cleaning', 'Cleaning(تنظيف'), ('Carpenter', 'Carpenter(نجارة)'), ('AC', 'AC(تكييف)'), ('Mason', 'Mason(بناء)'), ('Ceiling', 'Ceiling(سقف)'), ('Plumbing & Electric', 'Plumbing and Electric')], max_length=50),
        ),
    ]
