# Generated by Django 5.2.14 on 2026-08-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0046_alter_task_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceworkitem',
            name='project_type',
            field=models.CharField(choices=[('Paint', 'Paint(صباغة)'), ('Electric', 'Electric(كهرباء)'), ('Plumbing', 'Plumbing(سباكة)'), ('Cleaning', 'Cleaning(تنظيف'), ('Carpenter', 'Carpenter(نجارة)'), ('AC', 'AC(تكييف)'), ('Mason', 'Mason(بناء)'), ('Ceiling', 'Ceiling(سقف)'), ('Plumbing and Electric', 'Plumbing and Electric')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_type',
            field=models.CharField(choices=[('Paint', 'Paint(صباغة)'), ('Electric', 'Electric(كهرباء)'), ('Plumbing', 'Plumbing(سباكة)'), ('Cleaning', 'Cleaning(تنظيف'), ('Carpenter', 'Carpenter(نجارة)'), ('AC', 'AC(تكييف)'), ('Mason', 'Mason(بناء)'), ('Ceiling', 'Ceiling(سقف)'), ('Plumbing and Electric', 'Plumbing and Electric')], max_length=50),
        ),
    ]
