# Generated by Django 5.2.14 on 2026-08-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0047_alter_maintenanceworkitem_project_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('building', 'unit')},
            },
        ),
    ]
