# Generated by Django 5.2.14 on 2026-08-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0048_blacklistedunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedUnit',
        ),
    ]
