# Generated by Django 5.2.14 on 2026-08-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0050_blacklistedunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedunit',
            name='reason',
            field=models.TextField(blank=True, help_text='Optional reason for blacklisting', null=True),
        ),
    ]
